export const data= [
    {    
            TCTNo: '001',
        	Name:  'Chaz Panossian',
            Address:'Mati City',
            PlateNo:'FE433T',
            MakeofVehicle:'Toyota',
            TypeofVehicle:'4 wheels',
            RegisteredOwner:'Chaz Panossian',
            Address:'Mati City',
            Violation:'No Helmet, No Lisence',
            ViolatorOfficer:'James Dou',
            DateTimeofApprehetion:'2:10pm/11/2/2020',
            PlaceofApprehension:'Madang',
        	Payment:'Unpaid',
    },
    {
        TCTNo: '002',
        Name:  'Chaz Panossian',
        Address:'Mati City',
        PlateNo:'FE433T',
        MakeofVehicle:'Toyota',
        TypeofVehicle:'4 wheels',
        RegisteredOwner:'Chaz Panossian',
        Address:'Mati City',
        Violation:'No Helmet, No Lisence',
        ViolatorOfficer:'James Dou',
        DateTimeofApprehetion:'2:10pm/11/2/2020',
        PlaceofApprehension:'Madang',
        Payment:'Unpaid',
},    {
    TCTNo: '003',
    Name:  'Chaz Panossian',
    Address:'Mati City',
    PlateNo:'FE433T',
    MakeofVehicle:'Toyota',
    TypeofVehicle:'4 wheels',
    RegisteredOwner:'Chaz Panossian',
    Address:'Mati City',
    Violation:'No Helmet, No Lisence',
    ViolatorOfficer:'James Dou',
    DateTimeofApprehetion:'2:10pm/11/2/2020',
    PlaceofApprehension:'Madang',
    Payment:'Unpaid',
},    {
    TCTNo: '004',
    Name:  'Chaz Panossian',
    Address:'Mati City',
    PlateNo:'FE433T',
    MakeofVehicle:'Toyota',
    TypeofVehicle:'4 wheels',
    RegisteredOwner:'Chaz Panossian',
    Address:'Mati City',
    Violation:'No Helmet, No Lisence',
    ViolatorOfficer:'James Dou',
    DateTimeofApprehetion:'2:10pm/11/2/2020',
    PlaceofApprehension:'Madang',
    Payment:'Unpaid',
},    {
    TCTNo: '005',
    Name:  'Chaz Panossian',
    Address:'Mati City',
    PlateNo:'FE433T',
    MakeofVehicle:'Toyota',
    TypeofVehicle:'4 wheels',
    RegisteredOwner:'Chaz Panossian',
    Address:'Mati City',
    Violation:'No Helmet, No Lisence',
    ViolatorOfficer:'James Dou',
    DateTimeofApprehetion:'2:10pm/11/2/2020',
    PlaceofApprehension:'Madang',
    Payment:'Unpaid',
}

    
]
export default data;